receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  otlphttp/axiom:
    endpoint: "https://api.axiom.co"
    headers:
      authorization: "Bearer ${env:AXIOM_TOKEN}"
      x-axiom-dataset: "${env:AXIOM_DATASET}"

  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlphttp/axiom, debug]